### ISSUE TITLE
get_plugin_data function not defined.

### ISSUE THREAD

**Issue by danbleile** [washingtonstateuniversity/WSUWP-Plugin-A11y-Status#14] opened 2019-03-29 17:03 UTC
Looks like get_pluign_data is being called on 'plugins_loaded' https://github.com/washingtonstateuniversity/WSUWP-Plugin-A11y-Status/blob/6a1bec8c17117a0a5cd4c89deda6e425394e5dee/wsuwp-a11y-status.php#L28

get_plugin_data is only available in admin and plugins_loaded gets called on the front end as well.

**Comment by admturner** [comment] 2019-04-04 16:01
It does look like this could the the issue, though I'm a little confused as it triggering on plugin activation, which should happen only in the admin area. In any case it's something that should be fixed.

1. I considered loading on an admin-only hook like `admin_init`, but it fires after the user is already authenticated and logged in, so it's too late for the `wp_login` action to fire.
2. I also tried adding an `is_admin` check to the `load_wsuwp_a11y_status` setup function, but `is_admin` returns false on the /wp-login.php page, which again broke the `wp_login` action. (And including a check for the login page using the `GLOBALS` variable caused some unknown problems.)
3. The potential solution I landed on - implemented in the [fix-login-activate-issues](https://github.com/washingtonstateuniversity/WSUWP-Plugin-A11y-Status/tree/fix-login-activate-issues) branch - is to move the call to `get_plugin_data` from the plugin setup method into the admin scripts method, which should only fire in the admin area.

I'm concerned there may still be another issue at the root of the activation error, but so far I can't reproduce it in any of my environments. If it happens again could you post the error message here?

**Closed** 2019-08-05 15:31 UTC
Labels: bug
